name: ci

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile

            - name: Check formatting & linting
              run: bun run ci

            - name: Typecheck
              run: bun run typecheck

            - name: Build
              run: bun run build

            - name: Smoke test
              run: bun run dist/cli.js --help
