name: ci

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile

            - name: Check formatting & linting
              run: bun run ci

            - name: Check markdown formatting
              run: npx prettier@3 --check README.md

            - name: Typecheck
              run: bun run typecheck

            - name: Test
              run: bun run test

            - name: Check config schema is up to date
              run: bun run config-json-schema:update && git diff --exit-code src/config/schema.json

            - name: Build
              run: bun run build

            - name: Smoke test
              run: bun run dist/cli.js --help
